package frc.robot.subsystems.drive;

import static org.wpilib.units.Units.*;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModule.SteerRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import org.wpilib.math.linalg.Matrix;
import org.wpilib.math.geometry.Pose2d;
import org.wpilib.math.geometry.Rotation2d;
import org.wpilib.math.geometry.Translation2d;
import org.wpilib.math.geometry.Translation3d;
import org.wpilib.math.kinematics.ChassisVelocities;
import org.wpilib.math.numbers.N1;
import org.wpilib.math.numbers.N3;
import org.wpilib.networktables.DoubleArrayPublisher;
import org.wpilib.networktables.DoubleArraySubscriber;
import org.wpilib.networktables.NetworkTable;
import org.wpilib.networktables.NetworkTableEvent;
import org.wpilib.networktables.NetworkTableInstance;
import org.wpilib.networktables.NetworkTableValue;
import org.wpilib.networktables.NetworkTablesJNI;
import org.wpilib.networktables.StructArrayPublisher;
import org.wpilib.networktables.StructPublisher;
import org.wpilib.driverstation.MatchState;
import org.wpilib.driverstation.RobotState;
import org.wpilib.driverstation.Alliance;
import org.wpilib.driverstation.MatchType;
import org.wpilib.driverstation.DriverStationErrors;
import org.wpilib.driverstation.Alliance;
import org.wpilib.system.Notifier;
import org.wpilib.system.RobotController;
import org.wpilib.command2.Command;
import org.wpilib.command2.Subsystem;
import org.wpilib.command2.sysid.SysIdRoutine;
import frc.robot.Constants.FieldConstants;
import frc.robot.Constants.VisionConstants;
import frc.robot.subsystems.drive.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.drive.requests.ResettableSwerveRequest;
import java.util.EnumSet;
import java.util.Optional;
import java.util.function.Supplier;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
  private static final double kSimLoopPeriod = 0.004; // 4 ms
  private Notifier m_simNotifier = null;
  private double m_lastSimTime;

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.ZERO;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective = false;

  /*Swerve request to apply during robot-centric path following */

  private final SwerveRequest.ApplyRobotVelocity m_pathApplyRobotVelocity =
    new SwerveRequest.ApplyRobotVelocity()
        .withDriveRequestType(DriveRequestType.Velocity)
        .withSteerRequestType(SteerRequestType.Position);


  /* Swerve requests to apply during SysId characterization */
  private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization =
      new SwerveRequest.SysIdSwerveTranslation();
  private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization =
      new SwerveRequest.SysIdSwerveSteerGains();
  private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization =
      new SwerveRequest.SysIdSwerveRotation();
  private final SwerveRequest.SysIdSwerveTranslation m_slipCurrentCharacterization =
      new SwerveRequest.SysIdSwerveTranslation();

  /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
  private final SysIdRoutine m_sysIdRoutineTranslation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null, // Use default ramp rate (1 V/s)
              Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
          new SysIdRoutine.Mechanism(
              output -> setControl(m_translationCharacterization.withVolts(output)), null, this));

  /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
  private final SysIdRoutine m_sysIdRoutineSteer =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null, // Use default ramp rate (1 V/s)
              Volts.of(7), // Use dynamic voltage of 7 V
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
          new SysIdRoutine.Mechanism(
              volts -> setControl(m_steerCharacterization.withVolts(volts)), null, this));

  /*
   * SysId routine for characterizing rotation.
   * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
   * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
   */
  private final SysIdRoutine m_sysIdRoutineRotation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              /* This is in radians per second², but SysId only supports "volts per second" */
              Volts.of(Math.PI / 6).per(Second),
              /* This is in radians per second, but SysId only supports "volts" */
              Volts.of(Math.PI),
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
          new SysIdRoutine.Mechanism(
              output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
              },
              null,
              this));

  /**
   * Sysid routine for charaterizing slip current. You must log the data yourself while the test is
   * running.
   */
  private final SysIdRoutine m_sysIdRoutineSlipCurrent =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              Volts.of(0.1).per(Second),
              Volts.of(0),
              null // Use default timeout (10s)
              ,
              state -> {}),
          new SysIdRoutine.Mechanism(
              output -> setControl(m_slipCurrentCharacterization.withVolts(output)), null, this));

  /* The SysId routine to test */
  private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineSteer;

  /*Networktables for logging */
  private final NetworkTableInstance m_inst = NetworkTableInstance.getDefault();

  /**
   * This NetworkTable is used to display driving information to AdvantageScope. Open <a
   * href="https://docs.advantagescope.org/tab-reference/odometry">the AdvantageScope docs</a> to
   * see what this looks like.
   */
  private final NetworkTable m_stateTable = m_inst.getTable("DriveState");

  private final NetworkTable m_poseTable = m_stateTable.getSubTable("Poses");

  private final NetworkTable m_driveTemps = m_stateTable.getSubTable("Drive Temperatures");

  /** Logs the front bot pose estimate to AdvantageScope. */
  private final StructPublisher<Pose2d> m_frontPoseEstimatePub =
      m_poseTable.getStructTopic("Front Pose Estimate", Pose2d.struct).publish();

  // private final StructPublisher<Pose2d> m_backPoseEstimatePub =
  //     m_poseTable.getStructTopic("Back Pose Estimate", Pose2d.struct).publish();

  private final NetworkTable m_speedsTable = m_stateTable.getSubTable("Speeds");
  private final StructPublisher<ChassisVelocities> m_appliedSpeedsPub =
      m_speedsTable
          .getStructTopic("PathPlanner Applied Robot-relative Speeds", ChassisVelocities.struct)
          .publish();

  private final NetworkTable m_tagsTable = m_stateTable.getSubTable("Apriltags");

  /** Logs the tags that are currently visible from the front to AdvantageScope. */
  private final StructArrayPublisher<Translation3d> m_frontVisibleTagsPub =
      m_tagsTable.getStructArrayTopic("Front Visible Tags", Translation3d.struct).publish();

  private final DoubleArrayPublisher m_frontToTagDistancePub =
      m_tagsTable.getDoubleArrayTopic("Tag Distance to Front Camera").publish();

  // private final StructArrayPublisher<Translation3d> m_backVisibleTagsPub =
  //     m_tagsTable.getStructArrayTopic("Back Visible Tags", Translation3d.struct).publish();
  // private final DoubleArrayPublisher m_backToTagDistancePub =
  //     m_tagsTable.getDoubleArrayTopic("Tag Distance to Front Camera").publish();

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }
    configureAutoBuilder();
    registerPoseEstimateListeners();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, odometryUpdateFrequency, modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }
    configureAutoBuilder();
    registerPoseEstimateListeners();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
   *     [x, y, theta]ᵀ, with units in meters and radians
   * @param visionStandardDeviation The standard deviation for vision calculation in the form [x, y,
   *     theta]ᵀ, with units in meters and radians
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(
        drivetrainConstants,
        odometryUpdateFrequency,
        odometryStandardDeviation,
        visionStandardDeviation,
        modules);
    if (Utils.isSimulation()) {
      startSimThread();
    }
    configureAutoBuilder();
    registerPoseEstimateListeners();
  }

  private void configureAutoBuilder() {
   
    AutoBuilder.configure(
        () -> getState().Pose, // Supplier of current robot pose
        this::resetPose, // Consumer for seeding pose against auto
        () -> getState().Velocity, // Supplier of current robot speeds
        // Consumer of ChassisVelocities and feedforwards to drive the robot
        (speeds, feedforwards) -> {
          ;
          setControl(
              m_pathApplyRobotVelocity
                  .withVelocity(speeds)
                  .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                  .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons()));
        },
        new PPHolonomicDriveController(DriveConstants.TRANSLATION_PID, DriveConstants.ROTATION_PID),
        DriveConstants.PATHPLANNER_CONFIG,
        // Assume the path needs to be flipped for Red vs Blue, this is normally the case
        () -> MatchState.getAlliance().orElse(Alliance.BLUE) == Alliance.RED,
        this // Subsystem for requirements
        );

  }

  /**
   * Returns a command that applies the specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  /**
   * Returns a command that resets the swerve request's controller/controllers and applies the
   * specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyResettableRequest(Supplier<ResettableSwerveRequest> requestSupplier) {
    return this.startRun(
        () -> requestSupplier.get().resetRequest(), () -> this.setControl(requestSupplier.get()));
  }

  /**
   * Runs the SysId Quasistatic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Quasistatic test
   * @return Command to run
   */
  public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.quasistatic(direction);
  }

  /**
   * Runs the SysId Dynamic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Dynamic test
   * @return Command to run
   */
  public Command sysIdDynamic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.dynamic(direction);
  }

@Override
public void periodic() {
    /*
     * Periodically try to apply the operator perspective.
     * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
     * This allows us to correct the perspective in case the robot code restarts mid-match.
     * Otherwise, only check and apply the operator perspective if the DS is disabled.
     * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
     */

    if (!m_hasAppliedOperatorPerspective || RobotState.isDisabled()) {
      MatchState.getAlliance()
          .ifPresent(
              allianceColor -> {
                setOperatorForwardDirection(
                    allianceColor == Alliance.RED
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
              });
    }
  }

  private void startSimThread() {
    m_lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier =
        new Notifier(
            () -> {
              final double currentTime = Utils.getCurrentTimeSeconds();
              double deltaTime = currentTime - m_lastSimTime;
              m_lastSimTime = currentTime;

              /* use the measured time delta, get battery voltage from WPILib */
              updateSimState(deltaTime, RobotController.getBatteryVoltage());
            });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  /**
   * Registers the limelight pose listeners, so the poses can be used as soon as they are recieved
   * from the limelights.
   *
   * @see frc.robot.util.LimelightHelpers#getBotPoseEstimate(String, String, boolean) the reference
   *     code for processing the input from this NetworkTable entry
   * @see <a
   *     href="https://docs.wpilib.org/en/stable/docs/software/networktables/listening-for-change.html">the
   *     explanation for listeners</a>
   * @see <a
   *     href="https://docs.limelightvision.io/docs/docs-limelight/apis/complete-networktables-api#apriltag-and-3d-data">the
   *     limelight NetworkTables API</a> (look for botpose_orb_wpiblue)
   */
  private void registerPoseEstimateListeners() {
    DoubleArraySubscriber frontPoseEstimateSub =
        m_inst
            .getTable(VisionConstants.FRONT_LIMELIGHT_NAME)
            .getDoubleArrayTopic("botpose_orb_wpiblue")
            .subscribe(null);

    m_inst.addListener(
        frontPoseEstimateSub,
        EnumSet.of(NetworkTableEvent.Kind.VALUE_ALL),
        event -> {
          NetworkTableValue value = event.valueData.value;
          double[] poseArray = value.getDoubleArray();
          // If there is no data available, don't use the data.
          if (poseArray.length < 11) {
            m_frontVisibleTagsPub.set(FieldConstants.NO_VISIBLE_TAGS);
            m_frontToTagDistancePub.set(FieldConstants.NO_TAG_DISTANCES);
            return;
          }

          /*Get bot pose estimate */
          Translation2d botPose = new Translation2d(poseArray[0], poseArray[1]);
          // Whenever the robot doesn't see any tags, it will send a pose of (0,0,0)
          if (botPose.equals(Translation2d.ZERO)) {
            m_frontVisibleTagsPub.set(FieldConstants.NO_VISIBLE_TAGS);
            return;
          }
          Rotation2d botRotation = Rotation2d.fromDegrees(poseArray[5]);
          Pose2d botPoseEstimate = new Pose2d(botPose, botRotation);

          /* Get timestamp */
          long timestampNanoseconds = value.getTime();

          /* Log pose estimate to AdvantageScope */
          m_frontPoseEstimatePub.set(botPoseEstimate, timestampNanoseconds);

          // Convert the NetworkTables timestamp to the CTRE current-time timebase
          // and adjust for Limelight latency.
          double latencySeconds = poseArray[6] / 1000.0;

          double ntNowSeconds = NetworkTablesJNI.now() / 1_000_000_000.0;
          double ctreNowSeconds = Utils.getCurrentTimeSeconds();

          double visionTimestampSeconds =
              ctreNowSeconds
                  - (ntNowSeconds - timestampNanoseconds / 1_000_000_000.0)
                  - latencySeconds;

          /*Log which apriltags are currently visible */
          int tagCount = (int) poseArray[7];
          int valsPerFiducial = 7;
          int expectedTotalVals = 11 + valsPerFiducial * tagCount;

          // If there is no more data available, stop logging
          if (poseArray.length != expectedTotalVals || tagCount == 0) {
            m_frontVisibleTagsPub.set(FieldConstants.NO_VISIBLE_TAGS);
            m_frontToTagDistancePub.set(FieldConstants.NO_TAG_DISTANCES);
            return;
          }

          Translation3d[] visibleTagPositions = new Translation3d[tagCount];
          double[] distanceToTags = new double[tagCount];
          for (int i = 0; i < tagCount; i++) {
            int currentIndex = 11 + (i * valsPerFiducial);
            int id = (int) poseArray[currentIndex];
            double distance = poseArray[currentIndex + 4];
            visibleTagPositions[i] =
                FieldConstants.PLAYING_FIELD.getTagPose(id).orElseThrow().getTranslation();
            distanceToTags[i] = distance;
          }
          m_frontVisibleTagsPub.set(visibleTagPositions, timestampNanoseconds);
          m_frontToTagDistancePub.set(distanceToTags, timestampNanoseconds);

          /* Add the vision measurement to the pose estimator */
          // SYSTEMCORE: Verify NT local-time epoch matches CTRE current-time epoch.
          this.addVisionMeasurement(
              botPoseEstimate,
              visionTimestampSeconds,
              VisionConstants.FRONT_STD_DEVS);
        });
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds.
   */
  /* SYSTEMCORE BEGIN
  @Override
  public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
    super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
  }
  SYSTEMCORE END */

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * <p>Note that the vision measurement standard deviations passed into this method will continue
   * to apply to future measurements until a subsequent call to {@link
   * #setVisionMeasurementStdDevs(Matrix)} or this method.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds.
   * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement in the form
   *     [x, y, theta]ᵀ, with units in meters and radians.
   */
  /* SYSTEMCORE BEGIN
  @Override
  public void addVisionMeasurement(
      Pose2d visionRobotPoseMeters,
      double timestampSeconds,
      Matrix<N3, N1> visionMeasurementStdDevs) {
    super.addVisionMeasurement(
        visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
  }
  SYSTEMCORE END */

  /**
   * Return the pose at a given timestamp, if the buffer is not empty.
   *
   * @param timestampSeconds The timestamp of the pose in seconds.
   * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
   */
  /* SYSTEMCORE BEGIN
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
  }
    SYSTEMCORE END */
}
